### PR TITLE
 Change base image to tomcat:8.5-jdk8, as Alpine Linux base is no longer supported

### PR DESCRIPTION
**Pull request by MattBlissett**

### CODE REVIEW

**Comment by ckotwn** [comment]
Hi Matt - tried to build here and see:
```
ocker-ipt on  debian on 🐳 v19.03.2
➜ docker build --tag=gbifipt .
Sending build context to Docker daemon  3.584kB
Step 1/9 : FROM tomcat:8.5-jdk8
8.5-jdk8: Pulling from library/tomcat
092586df9206: Pull complete
ef599477fae0: Pull complete
4530c6472b5d: Pull complete
d34d61487075: Pull complete
272f46008219: Pull complete
12ff6ccfe7a6: Pull complete
f26b99e1adb1: Pull complete
21bec9c8ea28: Pull complete
e2f6023231f2: Pull complete
c47eb491a5e3: Pull complete
Digest: sha256:74e52cc6d27dacb079b273c129d6bf32df6ba328d6508b81ef65f41675ae9570
Status: Downloaded newer image for tomcat:8.5-jdk8
 ---> 365b0a528e2e
Step 2/9 : LABEL MAINTAINERS="Markus Döring <mdoering@gbif.org>, Matthew Blissett <mblissett@gbif.org>"
 ---> Running in a7ab66789952
Removing intermediate container a7ab66789952
 ---> 674b53856d43
Step 3/9 : ARG IPT_VERSION
 ---> Running in b11f6956f3f9
Removing intermediate container b11f6956f3f9
 ---> 2b4a70b74b22
Step 4/9 : ARG IPT_NAME=ROOT
 ---> Running in 14c4ed7395d3
Removing intermediate container 14c4ed7395d3
 ---> b8ecc1be280f
Step 5/9 : ENV IPT_DATA_DIR=/srv/ipt
 ---> Running in 5d822626fd81
Removing intermediate container 5d822626fd81
 ---> f5b3f7040938
Step 6/9 : RUN rm -Rf /usr/local/tomcat/webapps     && mkdir -p /usr/local/tomcat/webapps/${IPT_NAME}     && mkdir -p ${IPT_DATA_DIR}     && curl -LSsfo ipt.war https://repository.gbif.org/repository/releases/org/gbif/ipt/${IPT_VERSION}/ipt-${IPT_VERSION}.war     && unzip -d /usr/local/tomcat/webapps/${IPT_NAME} ipt.war     && rm -f ipt.war
 ---> Running in d70c32235e7f
curl: (22) The requested URL returned error: 404 org/gbif/ipt/ipt-.war
The command '/bin/sh -c rm -Rf /usr/local/tomcat/webapps     && mkdir -p /usr/local/tomcat/webapps/${IPT_NAME}     && mkdir -p ${IPT_DATA_DIR}     && curl -LSsfo ipt.war https://repository.gbif.org/repository/releases/org/gbif/ipt/${IPT_VERSION}/ipt-${IPT_VERSION}.war     && unzip -d /usr/local/tomcat/webapps/${IPT_NAME} ipt.war     && rm -f ipt.war' returned a non-zero code: 22
```

**Comment by frafra** [comment]
Could it be rebased against master?

**Comment by frafra** [comment]
What about using the slim variant?

**Comment by MattBlissett** [comment]
I've decided not to use the slim variant, as the documentation recommends against it.

**Pull request merged**
